### ISSUE TITLE
Bot stops after castling

### ISSUE THREAD

**Issue by erxson** [vaezim/Online-Chess-cheater-Bot#4]
Opponent does castling and bot just freezes

**Comment by erxson** [comment]
![image](https://user-images.githubusercontent.com/50082485/218257429-cbf681be-e778-4dd6-b0be-ff461599914a.png)
freeze again, but without o-o

**Comment by vaezim** [comment]
This happens when the bot enters the move before the move animation on lichess is completed. I have to think of sth for it but if you enter the move manually the bot will continue.

**Comment by vaezim** [comment]
Looks like freezes are fixed :|
